/**
 * Generates supabase/seed.sql from src/data/seed for the catalogue tables.
 * Users, attempts, payments etc. are skipped: auth users are created via Supabase Auth.
 * Run: npm run seed:sql
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { getSeedData } from "../src/data/seed";

const TABLES = ["subjects", "exams", "books", "notes", "previous_year_papers", "questions", "mock_tests", "mock_test_questions", "announcements", "settings"] as const;
const JSONB: Record<string, string[]> = {
  exams: ["eligibility", "syllabus", "exam_pattern", "study_plan", "important_question_ids"],
  settings: ["value"],
};
const TEXT_ARRAY: Record<string, string[]> = { books: ["exam_ids"], notes: ["exam_ids"] };
const PK: Record<string, string> = { settings: "key" };

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

function literal(table: string, col: string, v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (JSONB[table]?.includes(col)) return `${q(JSON.stringify(v))}::jsonb`;
  if (TEXT_ARRAY[table]?.includes(col)) return `ARRAY[${(v as string[]).map(q).join(",")}]::text[]`;
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (typeof v === "string") return q(v);
  return q(JSON.stringify(v));
}

const data = getSeedData();
let out = "-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.\nbegin;\n\n";
for (const table of TABLES) {
  const rows = data[table] as unknown as Record<string, unknown>[];
  if (!rows.length) continue;
  const cols = Object.keys(rows[0]);
  out += `-- ${table} (${rows.length} rows)\n`;
  for (let i = 0; i < rows.length; i += 100) {
    const chunk = rows.slice(i, i + 100);
    out += `insert into public.${table} (${cols.join(", ")}) values\n`;
    out += chunk.map((r) => `  (${cols.map((c) => literal(table, c, r[c])).join(", ")})`).join(",\n");
    out += `\non conflict (${PK[table] ?? "id"}) do nothing;\n`;
  }
  out += "\n";
}
out += "commit;\n";
const file = path.join(process.cwd(), "supabase", "seed.sql");
writeFileSync(file, out);
console.log(`Wrote ${file} (${(out.length / 1024).toFixed(0)} KB)`);
